#!/usr/bin/env python

import sys
import string

ns = '22233344455566677778889999'
converted = sys.argv[1].translate(str.maketrans(string.ascii_lowercase, ns))
print(converted[:-4]+'-'+converted[-4:])
